name: Build and Deploy Angular Shell Microfrontend

on:
  push:
    branches:
      - workflow # Runs on push to workflow branch
  pull_request:
    branches:
      - workflow # Runs on PR to workflow branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust to match your Angular version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration=production

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-shell-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-shell-build
          path: dist/

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: dist/
